name: start_new_deal

on:
#  push:
#    branches:
#      - master
  schedule:
    - cron: '*/5 * * * *' # every 5 minute

jobs:
  start_deals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: pip install
        run: pip install -r requirements.txt
      - name: get started
        run: python main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET: ${{ secrets.SECRET }}