name: update bots

on:
  issues:
    types: [opened, edited]

jobs:
  start_deals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - name: show issue body
        run: echo ${{ github.event.issue.body }}